name: Build LaTeX and Deploy PDF to pdf-output

on:
  push:
    branches:
      - main  # Only trigger on the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: danteev/texlive  # A Docker image with LaTeX pre-installed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Compile LaTeX to PDF using xelatex
        run: |
          latexmk -pdf -xelatex -interaction=nonstopmode SaidnassimovDarkhanCV.tex

      - name: Upload compiled PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-cv
          path: SaidnassimovDarkhanCV.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download compiled PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-cv
          path: ./  # Downloads the PDF to the repository

      - name: Setup output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOYMENT_KEY }}@github.com/darkhan-s/myCV.git
          git checkout -B pdf-output origin/pdf-output || git checkout --orphan pdf-output
          
          # Remove all files except README.md
          find . -not -name 'README.md' -not -name '.git' -exec rm -rf {} +
          
          # Add README.md and the PDF
          git add README.md SaidnassimovDarkhanCV.pdf
          git commit -m "Deploy compiled CV PDF and keep README.md"
          
          # Force push to pdf-output branch
          git push --force origin pdf-output


        env:
          GITHUB_TOKEN: ${{secrets.DEPLOYMENT_KEY}}