name: Build LaTeX and Deploy PDF to pdf-output

on:
  push:
    branches:
      - main  # Only trigger on the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: danteev/texlive  # A Docker image with LaTeX pre-installed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Compile LaTeX to PDF using xelatex
        run: |
          latexmk -pdf -xelatex -interaction=nonstopmode SaidnassimovDarkhanCV.tex

      - name: Upload compiled PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-cv
          path: SaidnassimovDarkhanCV.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download compiled PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-cv
          path: ./  # Downloads the PDF to the repository

      - name: Setup output branch
        run: |
          # Set the correct remote URL using the PAT
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOYMENT_KEY }}@github.com/darkhan-s/myCV.git
          # Fetch all branches
          git fetch origin

          # Check out the pdf-output branch (create if not exists)
          git checkout -B pdf-output

          # Copy all files from main to pdf-output
          git checkout main -- .
          
          # Add all files including the new PDF
          git add .
          git commit -m "Update with latest build"

          # Push changes to pdf-output branch
          git push --force origin pdf-output

        env:
          GITHUB_TOKEN: ${{secrets.DEPLOYMENT_KEY}}